[package]
name = "pytoon"
version = "0.1.2"
edition = "2021"

[lib]
name = "toon"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
serde_json = "1.0"

[dependencies.toon]
path = ".."
